version: '3.8'

services:
  db:
    image: postgres
    healthcheck:
      test: ["CMD","pg_isready","-U","user", "-d", "CaitsDB"]
      interval: 15s
      timeout: 45s
      retries: 3
    restart: always
    volumes:
      - ./src/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: user
      POSTGRES_DB: CaitsDB
    ports:
      - "5432:5432"
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://user:pwd@db:5432/CaitsDB
    depends_on:
       db:
          condition: service_healthy