version: '3.9'

services:
  test-db:
    image: postgres:latest
    healthcheck:
      test: [ "CMD","pg_isready","-U","testuser", "-d", "testdb" ]
      interval: 15s
      timeout: 45s
      retries: 3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpwd
