version: '3.9'

services:
  db:
    image: postgres:latest
    healthcheck:
      test: ["CMD","pg_isready","-U","user", "-d", "CaitsDB"]
      interval: 15s
      timeout: 45s
      retries: 3
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: CaitsDB
    ports:
      - "5432:5432"
  api:
    build: .
    environment:
       DATABASE_URL: postgres://user:password@db:5432/CaitsDB
    ports:
      - "8080:8080"
    depends_on:
       db:
          condition: service_healthy
